
# File di configurazione

[COMMON]
sovrascrivi = True
area = (7.45, 10.1, 43.75, 44.7)
cartella_destinazione = /home/cfmi.arpal.org/daniele.carnevale/Scrivania/MeteoBricchi/dati2D
# cartella_destinazione = /media/daniele/Daniele2TB/repo/MeteoBricchi/dati2D

# freq obbligatoria a non meno di 30min
freq = 30min

[HEATINDEX2D_OBS]
lapse_rate_T = 0.0065
lapse_rate_d = 0.002

[WINDCHILL2D_OBS]
lapse_rate_T = 0.0065
